# Use the python 3.8 base image
FROM python:3.8

# Copy the Python client script into the container
COPY client.py /app/client.py

# Set the working directory
WORKDIR /app

# Run the Python client script
CMD ["python", "client.py"]
